import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../entities/bill.dart';

class BillReportService {
  static Future<void> generateAndPrintReport({
    required List<Bill> bills,
    required String userName,
    required Map<String, String> chatRoomNames,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateFormat = DateFormat('dd MMM yyyy');
    final currencyFormat = NumberFormat.currency(symbol: 'RM ');

    // Calculate Category Totals
    final Map<BillType, double> categoryTotals = {};
    for (var bill in bills) {
      categoryTotals[bill.type] = (categoryTotals[bill.type] ?? 0) + bill.amount;
    }

    // Calculate Group Totals
    final Map<String, double> groupTotals = {};
    for (var bill in bills) {
      final roomName = chatRoomNames[bill.chatRoomId] ?? 'Unknown Group';
      groupTotals[roomName] = (groupTotals[roomName] ?? 0) + bill.amount;
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Header
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Pulse Shared Bills Report',
                        style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
                    pw.SizedBox(height: 4),
                    pw.Text('Generated by: $userName'),
                    pw.Text('Date: ${dateFormat.format(now)}'),
                  ],
                ),
                pw.PdfLogo(),
              ],
            ),
            pw.SizedBox(height: 32),

            // Summary Section
            pw.Text('Expense Summaries', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Divider(thickness: 1),
            pw.SizedBox(height: 16),

            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Category Summary Table
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('By Category', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 8),
                      pw.TableHelper.fromTextArray(
                        headers: ['Category', 'Total'],
                        data: categoryTotals.entries.map((e) => [
                          e.key.name.toUpperCase(),
                          currencyFormat.format(e.value),
                        ]).toList(),
                        headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                        headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
                      ),
                    ],
                  ),
                ),
                pw.SizedBox(width: 24),
                // Group Summary Table
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('By Group', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 8),
                      pw.TableHelper.fromTextArray(
                        headers: ['Group', 'Total'],
                        data: groupTotals.entries.map((e) => [
                          e.key,
                          currencyFormat.format(e.value),
                        ]).toList(),
                        headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                        headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            pw.SizedBox(height: 32),

            // Detailed List
            pw.Text('Detailed Bill List', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Divider(thickness: 1),
            pw.SizedBox(height: 16),

            pw.TableHelper.fromTextArray(
              headers: ['Title', 'Group', 'Due Date', 'Status', 'Amount'],
              data: bills.map((bill) => [
                bill.title,
                chatRoomNames[bill.chatRoomId] ?? 'Unknown',
                dateFormat.format(bill.dueDate),
                bill.status.name.toUpperCase(),
                currencyFormat.format(bill.amount),
              ]).toList(),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
              cellAlignment: pw.Alignment.centerLeft,
              columnWidths: {
                0: const pw.FlexColumnWidth(3),
                1: const pw.FlexColumnWidth(2),
                2: const pw.FlexColumnWidth(2),
                3: const pw.FlexColumnWidth(1.5),
                4: const pw.FlexColumnWidth(2),
              },
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Pulse_Bills_Report_${now.millisecondsSinceEpoch}.pdf',
    );
  }
}
